from fpdf import FPDF
import re
import os
import textwrap

# Default to the built-in core font
ACTIVE_FONT = "helvetica"

class ArticlePDF(FPDF):
    def header(self):
        self.set_font(ACTIVE_FONT, "B", 10)
        self.set_text_color(255, 75, 75)
        self.cell(100, 10, "YouTube to Insightful Article", align="L")

        self.set_font(ACTIVE_FONT, "", 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by AI", align="R")
        self.ln()

        self.set_draw_color(220, 220, 220)
        self.line(10, 20, 200, 20)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font(ACTIVE_FONT, "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def sanitize_unicode(text: str) -> str:
    """Replaces common unsupported Unicode characters with ASCII equivalents."""
    replacements = {
        '–': '-',   # en-dash
        '—': '-',   # em-dash
        '“': '"',   # smart double quote left
        '”': '"',   # smart double quote right
        '‘': "'",   # smart single quote left
        '’': "'",   # smart single quote right
        '…': '...', # ellipsis
        '\u200b': ''# zero-width space
    }
    for search, replace in replacements.items():
        text = text.replace(search, replace)
    return text


def clean_text(text: str) -> str:
    """Strips markdown and applies a safety net for long words."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    text = re.sub(r'<[^>]+>', '', text)
    
    # Force a space in uninterrupted strings (75+ chars) to prevent width crashes
    text = re.sub(r'([^\s]{75})', r'\1 ', text)
    
    return text.strip()


def create_pdf(article: str, video_title: str = "Insightful Article"):
    """Generates the PDF and returns bytes for Streamlit."""
    global ACTIVE_FONT
    
    try:
        # 1. Sanitize the text first to prevent font crashes!
        article = sanitize_unicode(article)
        video_title = sanitize_unicode(video_title)

        pdf = ArticlePDF()

        # Safe font path handling
        font_path = os.path.join(os.path.dirname(__file__), "DejaVuSans.ttf")
        
        if os.path.exists(font_path):
            pdf.add_font("DejaVu", "", font_path)
            pdf.add_font("DejaVu", "B", font_path) 
            ACTIVE_FONT = "DejaVu"
        else:
            ACTIVE_FONT = "helvetica"

        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.set_margins(15, 25, 15)

        pdf.add_page()

        # Video Title
        pdf.set_font(ACTIVE_FONT, "B", 16)
        pdf.set_text_color(0, 0, 0)
        wrapped_title = textwrap.wrap(video_title, width=50)
        for t_line in wrapped_title:
            pdf.multi_cell(0, 10, t_line)
        pdf.ln(5)

        lines = article.strip().split('\n')

        for line in lines:
            raw = line.strip()

            if not raw:
                pdf.ln(3)
                continue

            # H1
            if raw.startswith('# '):
                pdf.set_font(ACTIVE_FONT, "B", 18)
                pdf.set_text_color(255, 75, 75)
                pdf.multi_cell(0, 10, clean_text(raw[2:]))
                pdf.ln(4)

            # H2
            elif raw.startswith('## '):
                pdf.set_font(ACTIVE_FONT, "B", 13)
                pdf.set_text_color(50, 50, 150)
                pdf.multi_cell(0, 8, clean_text(raw[3:]))
                pdf.ln(2)

            # H3
            elif raw.startswith('### '):
                pdf.set_font(ACTIVE_FONT, "B", 11)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 7, clean_text(raw[4:]))
                pdf.ln(1)

            # Bullet points
            elif raw.startswith('- ') or raw.startswith('* '):
                pdf.set_font(ACTIVE_FONT, "", 10)
                pdf.set_text_color(40, 40, 40)
                pdf.set_x(20)
                pdf.cell(5, 6, "-")
                pdf.set_x(26)
                pdf.multi_cell(0, 6, clean_text(raw[2:]))
                pdf.ln(1)

            # Numbered list
            elif re.match(r'^\d+\.', raw):
                pdf.set_font(ACTIVE_FONT, "", 10)
                pdf.set_text_color(40, 40, 40)
                pdf.multi_cell(0, 6, clean_text(raw))
                pdf.ln(1)

            # Paragraph
            else:
                para = clean_text(raw)
                if para:
                    pdf.set_font(ACTIVE_FONT, "", 10)
                    pdf.set_text_color(40, 40, 40)
                    pdf.multi_cell(0, 7, para)
                    pdf.ln(2)

        pdf_bytes = bytes(pdf.output())
        return pdf_bytes, None

    except Exception as e:
        return None, str(e)